### ISSUE TITLE
it does not work after modify dev profile to use mysql

### ISSUE THREAD

**Issue by codepython** [hantsy/angularjs-springmvc-sample-boot#10]

**Comment by hantsy** [comment]
staging and  prod profiles used MySQL as database,  dev profile used embedded H2 by default. Read the pom file carefully.

You can copy the settings and define your profile as need.

**Comment by hantsy** [comment]
@codepython  BTW, if you know little about Spring profiles and Maven profiles, read the online book for the explanation of Maven profiles and Spring profiles.

https://hantsy.gitbooks.io/build-a-restful-app-with-spring-mvc-and-angularjs/content/getting-started/profile.html
