### ISSUE TITLE
able to run project but UI is not visible no log reported in the back 

### ISSUE THREAD

**Issue by maroom1** [hantsy/angularjs-springmvc-sample-boot#11]
![image](https://user-images.githubusercontent.com/12940280/28699696-170e6f1e-7300-11e7-8261-8010a978b139.png)

![image](https://user-images.githubusercontent.com/12940280/28699705-27ca534a-7300-11e7-9636-862b38893aa0.png)

![image](https://user-images.githubusercontent.com/12940280/28699726-3885c7dc-7300-11e7-951d-f57afe63d6ac.png)

![image](https://user-images.githubusercontent.com/12940280/28699742-4cfc3368-7300-11e7-9bc3-18a03a33869d.png)

I followed your steps 
npm install
bower install
mvn spring-boot:run -Dstatic-UI

**Comment by hantsy** [comment]
The `.addResourceLocations` line in `Application` destroyed the Spring Boot built-in url mapping rules, which was prepared for Docker mulitstages scenario. 

I will try to fix this later. 

Thanks for reporting this issue. @maroom1

**Comment by maroom1** [comment]
Thank you and waiting for the fix badly. Because I was inspired about your
project and implement some in my own project. Thanks for the propmt reply.
