### ISSUE TITLE
Unable to run gulp serve

### ISSUE THREAD

**Issue by pavangayakwad** [hantsy/angularjs-springmvc-sample-boot#13]
Was following instructions to run the source, was able to run Spring MVC on 9000 but angular gulp is failing.

Just wondering why gulp and not the simple neat "ng serve" 

Below is the error: 
![image](https://user-images.githubusercontent.com/1834890/66110799-23a81400-e5e5-11e9-97ba-0d9372c16a95.png)

and the CLI versions: 
![image](https://user-images.githubusercontent.com/1834890/66110939-6bc73680-e5e5-11e9-9ccd-9baff446b587.png)

**Comment by hantsy** [comment]
This project is under maintenance which used the legacy AngularJS(aka Angular 1.x),  no more new features added in the future. If you are looking for the new Spring Boot 2 and Angular 2+, check https://github.com/hantsy/angular-spring-reactive-sample

**Comment by pavangayakwad** [comment]
Ok. thanks for your swift reply! Let me check the new repo.
