### ISSUE TITLE
no setting.xml for docker deploy

### ISSUE THREAD

**Issue by yichaosun** [hantsy/angularjs-springmvc-sample-boot#14]
hi,bro
glad & honor to study with this project ,when I try to deploy with docker , I found there is no setting.xml in project, however ,the Dockerfile cmd with this file, I'm new to docker and nearly tow years far away from java. I can't handle with this, looking forward your help!

**Comment by hantsy** [comment]
This project is archived now, no new features/upgrades will be added in the future.  Check the [Docker section of Readme](https://github.com/hantsy/angularjs-springmvc-sample-boot#docker) and follow the steps to create Docker image and run it in Docker.

**Comment by yichaosun** [comment]
Thank u!
谢谢，老哥，应该也是中国人吧
