### ISSUE TITLE
Missing repo

### ISSUE THREAD

**Issue by steffenhohn** [hantsy/angularjs-springmvc-sample-boot#5]
Hi all
I tried to build the project but Maven was complaining about a missing artefact "swagger2markup-spring-restdocs-ext".
I just added the repo to pom.xml and everything was fine:

         <repository>
            <id>jcentral</id>
            <name>bintray</name>
            <url>http://jcenter.bintray.com</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

Thanks for the cool project.

Regards, S.

**Comment by hantsy** [comment]
fixed in https://github.com/hantsy/angularjs-springmvc-sample-boot/commit/756d198370ba0808281d4d4510baf0133e110cd7

Thanks @steffenhohn
