### ISSUE TITLE
Model Post_ don't exist

### ISSUE THREAD

**Issue by leeprovn** [hantsy/angularjs-springmvc-sample-boot#7]
Review in file with path ngularjs-springmvc-sample-boot/src/main/java/com/hantsylabs/restexample/springmvc/repository/PostSpecifications.java. The model Post_.java don't exist.
(import com.hantsylabs.restexample.springmvc.domain.Post_)

**Comment by hantsy** [comment]
explained in https://github.com/hantsy/angularjs-springmvc-sample/issues/3

Before use JPA , you have to learn the basic of JPA.
