### ISSUE TITLE
exec-maven-plugin can not run gulp when build in windows 

### ISSUE THREAD

**Issue by phxism** [hantsy/angularjs-springmvc-sample-boot#8]
when run this demo in windows ,   ```   mvn spring-boot:run -Dstatic-ui   ```,it gets an error :
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (g
ulp-build) on project angularjs-springmvc-sample-boot: Command execution failed.
 Cannot run program "C:\Users\HAP\AppData\Roaming\npm\gulp" (in directory "G:\IT
\Java_Samples\angularjs with spring\angularjs-springmvc-sample-boot-master"): Cr
eateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]`
因为 npm目录下有两个gulp和 gulp.cmd文件,当运行exec-maven-plugin插件的<executable>gulp</executable>命令时会先找到gulp文件而不是gulp.cmd.在windows系统下gulp文件是不能被执行的,换成使用groupId:com.github.eirslett artifactId:frontend-maven-plugin这个插件可以满足跨平台执行```   mvn spring-boot:run -Dstatic-ui   ```的需求.

**Comment by hantsy** [comment]
It seems it is a bug introduced in 1.5.0. https://github.com/mojohaus/exec-maven-plugin/issues/42

**Comment by hantsy** [comment]
It seems exec-maven-plugins has just released a new version 1.6.0, but it is not synced to Maven Center at the moment, I have tried it and make sure if it is fixed. 

@phxism  Form my opinion, the frontend maven plugin is not flexiable enough.  

Thanks for your reporting this issue.
